### ISSUE TITLE
Backend Node API for Autocomplete

### ISSUE THREAD

**Issue by nabeelahmadkh** [UIOWA5830SP19/SPP200#51]
Node API should respond with 5 similar courses for the autocomplete.
It should also have Performance Test.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nilbull** [comment]
useful link for different types of Elastic search queries: https://dzone.com/articles/23-useful-elasticsearch-example-queries

**Comment by nilbull** [comment]
How to create index in Elastic search : https://qbox.io/blog/an-introduction-to-ngrams-in-elasticsearch
